parameters:
#    class_central_static.example.class: ClassCentral\StaticBundle\Example

services:
#    class_central_static.example:
#        class: %class_central_static.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
