ClassCentralSiteBundle_homepage:
    pattern:  /
    defaults: { _controller: ClassCentralSiteBundle:Default:index }

ClassCentralSiteBundle_faq:
    pattern:  /faq
    defaults: { _controller: ClassCentralSiteBundle:Default:faq }

ClassCentralSiteBundle_courses:
    pattern:  /courses/{type}
    defaults: { _controller: ClassCentralSiteBundle:Default:courses }

ClassCentralSiteBundle_search:
  pattern: /search
  defaults: { _controller: ClassCentralSiteBundle:Search:index}  
  
ClassCentralSiteBundle_admin:
    resource: "@ClassCentralSiteBundle/Resources/config/routing_admin.yml"
    prefix: /admin    
