ClassCentral\SiteBundle\Entity\Course:
  type: entity
  table: courses
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 255
      fixed: false
      nullable: false
  ManyToOne:
    stream:
      targetEntity: Stream
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stream_id:
          referencedColumnName: id
      orphanRemoval: false
  ManyToMany:
    instructors:
      targetEntity: Stream
      join_table: 
        name: courses_instructors
        joinColumns:
          course_id:
             referencedColumnName: id
        inverseJoinColumns:
          instructor_id:
            referencedColumnName: id
  lifecycleCallbacks: {  }
