ClassCentral\SiteBundle\Entity\CoursesInstructors:
  type: entity
  table: courses_instructors
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
  oneToOne:
    course:
      targetEntity: Courses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        course_id:
          referencedColumnName: id
      orphanRemoval: false
    instructor:
      targetEntity: Instructors
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        instructor_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
