ClassCentral\SiteBundle\Entity\Course:
  type: entity
  table: courses
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
      fixed: false
      nullable: false   
  manyToOne:
    stream:
      targetEntity: Stream
      fetch: EAGER
      cascade: {  }      
      inversedBy: courses
      joinColumns:
        stream_id:
          referencedColumnName: id
      orphanRemoval: false  
    initiative:
      targetEntity: Initiative
      fetch: EAGER
      cascade: {}
      mappedBy: null
      inversedBy: courses
      orphanRemoval: false
      nullable: true
  oneToMany:
    offerings:
      targetEntity: Offering
      cascade: {  }
      mappedBy: course
      inversedBy: null    
      orphanRemoval: false
  manyToMany:    
    institutions:
      targetEntity: Institution
      inversedBy: courses      
      joinTable: 
        name: courses_institutions 
        joinColumns:
          course_id:
            referencedColumnName: id
        inverseJoinColumns:
          institution_id:
            referencedColumnName: id
      nullable: true        
  lifecycleCallbacks: {  }
