ClassCentral\SiteBundle\Entity\Course:
  type: entity
  table: courses
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
      fixed: false
      nullable: false   
  manyToOne:
    stream:
      targetEntity: Stream
      fetch: EAGER
      cascade: {  }      
      inversedBy: courses
      joinColumns:
        stream_id:
          referencedColumnName: id
      orphanRemoval: false  
  oneToMany:
    offerings:
      targetEntity: Offering
      cascade: {  }
      mappedBy: course
      inversedBy: null    
      orphanRemoval: false         
  lifecycleCallbacks: {  }
