ClassCentral\SiteBundle\Entity\Initiative:
  type: entity
  table: initiatives
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
      nullable: false
    url:
      type: string
      nullable: true
    description:
      type: string
      nullable: true
    code:
      type: string
      length: 20
      nullable: false
  oneToMany:
     offerings:
       targetEntity: Offering
       cascade: {}
       mappedBy: initiative
       inversedBy: null
       orphanRemoval: false