ClassCentral\SiteBundle\Entity\Instructor:
  type: entity
  table: instructors
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 100
      fixed: false
      nullable: false
    homepage:
      type: text
      nullable: true
  lifecycleCallbacks: {  }
