ClassCentral\SiteBundle\Entity\Offering:
  type: entity
  table: offerings
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    startDate:
      type: date
      nullable: true
      column: start_date
    endDate:
      type: date
      nullable: true
      column: end_date
    exactDatesKnow:
      type: boolean
      nullable: true
      column: exact_dates_know
    created:
      type: datetime
      nullable: true
    modified:
      type: datetime
      nullable: false   
    url:
      type: text
  manyToOne:
    course:
      targetEntity: Course
      cascade: {  }
      mappedBy: null
      inversedBy: offerings      
      orphanRemoval: false
  lifecycleCallbacks: {  }
