ClassCentral\SiteBundle\Entity\Stream:
  type: entity
  table: streams
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
      fixed: false
      nullable: true
    slug:
      type: string
      length: 255
      fixed: false
      nullable: true
    showInNav:
      type: boolean
      nullable: false
      column: show_in_nav
  oneToMany:
    courses:
      targetEntity: Course
      cascade: {  }
      mappedBy: stream      
      orphanRemoval: false    
  lifecycleCallbacks: {  }
